Release v3.2.4
nzzdev/Q-chart pull request #189
Opened 2020-09-15 15:45 UTC by manuelroth

- Handle null values in StackedBar charts

2020-09-15 16:06 UTC, romankaravia requested changes
Please see the comment about vega and keep the old version for now. I think for the other dependencies, it should be fine to update them.

2020-09-15 16:06 UTC, romankaravia commented on package.json
> +    "vega": "^5.15.0"
Unfortunately we depend on some implementation details of vega, so we cannot update right now, even if it is the same major version.

One example: https://github.com/nzzdev/Q-chart/blob/v3.2.3/chartTypes/commonPostprocessings.js#L16
This works for `style="opacity: 1"` in the output from vega, but not for `opacity="1"` (which I believe is something that has been changed in vega).

I don't remember the exact line of code, but one of these post-processings-gone-wrong also breaks [this chart](https://q.st-staging.nzz.ch/item/e9046b127bd99afc9cd208b94d0180cc), which I fixed in #183 (where I had to make sure that vega is kept at the same version).

Should we add this problem to our cleanup-todos? I am not sure yet, what the best solution would be to update: Either carefully checking fixtures and fixing things manually, or maybe this could be helped by automated tests with before/after visual comparisons.

2020-09-15 16:22 UTC, romankaravia commented on .dockerignore
> -node_modules
🤔 Are you sure we don't need this?

It looks like the `COPY . /app` line in the Dockerfile is now also copying `node_modules` from outside, in addition to the `node_modules` that is already there from the `npm install --production` inside the container. (before, this line only added ~ 1 MB)

<img width="408" alt="image" src="https://user-images.githubusercontent.com/47303530/93237243-2103e780-f780-11ea-9e68-6694955f9611.png">

2020-09-16 08:01 UTC, manuelroth commented on package.json
> +    "vega": "^5.15.0"
Okey I understand. I have created an issue describing the problem https://github.com/nzzdev/Q-chart/issues/190 and fixed the vega version in package.json https://github.com/nzzdev/Q-chart/pull/189/commits/3978c285d89969a0f0f3579dfd66981ba9c086a1.

2020-09-16 08:05 UTC, manuelroth commented on .dockerignore
> -node_modules
Oh I understand. I have added it back in https://github.com/nzzdev/Q-chart/pull/189/commits/99d7488a52f269b81afa05a0587047228a43126a

2020-09-16 08:50 UTC, romankaravia approved these changes
Looks all great now! Thank you for adding the todo as well.

Do you also want to tag and roll out the release or should I do it?

2020-09-16 10:10 UTC, merged